theme: jekyll-theme-hacker
title: CyCIF
description: A Public Domain Approach to Highly Multiplexed Cell and Tissue Imaging
sass:
    load_paths:
        - _scss
        - node_modules
plugins:
    - jekyll-redirect-from
exclude: []
